// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import { VmSafe } from "forge-std/Vm.sol";

/**
 * @title  Ledger
 * @notice `demo-native/state/ledger.json` — the native demo's memory between acts.
 *
 * @dev    WHY IT EXISTS. Each script is a separate process with no shared memory, so without a
 *         ledger every act would have to recompute or re-derive what the last one produced. Its
 *         real job is recovery: a failed step becomes resumable rather than fatal, which matters
 *         far more at a live demo than it does in a test.
 *
 *         READ, ASSERT, WRITE. Every script reads the keys it needs at the top and asserts them,
 *         naming any that are missing; every script writes its outputs before exiting.
 *
 *         NO NONCE LIVES HERE, AND THAT IS THE ONE DIFFERENCE FROM THE CROSS-CHAIN LEDGER. The
 *         wallet's agent-door lane counter is read from the chain with `wallet.getNonce(lane)`
 *         immediately before every signature, never cached. A stale sequence number produces a
 *         signature the wallet refuses with `InvalidNonce` — and in the cross-chain demo a
 *         hardcoded `nonceSeq = 0` in the grant script did exactly that on the second rehearsal.
 *         There is no `nonceSeq` key in this file; adding one would reintroduce that bug.
 *
 *         Gitignored: it is per-run state, regenerated by any rehearsal.
 */
library Ledger {
    VmSafe private constant vm = VmSafe(address(uint160(uint256(keccak256("hevm cheat code")))));

    string internal constant PATH = "demo-native/state/ledger.json";

    /// @dev Names the missing key and the script that writes it, so the remedy is on screen.
    error MissingLedgerKey(string key, string writtenBy);

    // ───────────────────────────────── reads ─────────────────────────────────

    /**
     * @notice Read an address, reverting if absent or zero.
     * @param key       Ledger key, e.g. "agw".
     * @param writtenBy The script that produces it, named in the error.
     */
    function addr(string memory key, string memory writtenBy) internal view returns (address) {
        string memory json = _read();
        string memory path = string.concat(".", key);
        if (!vm.keyExistsJson(json, path)) revert MissingLedgerKey(key, writtenBy);
        address a = vm.parseJsonAddress(json, path);
        if (a == address(0)) revert MissingLedgerKey(key, writtenBy);
        return a;
    }

    /**
     * @notice Read a uint, reverting if absent. Zero is a legitimate value here (`nonceSeq` starts
     *         at 0), so absence is the only failure — unlike `addr`, where zero is never valid.
     * @param key       Ledger key.
     * @param writtenBy The script that produces it.
     */
    function num(string memory key, string memory writtenBy) internal view returns (uint256) {
        string memory json = _read();
        string memory path = string.concat(".", key);
        if (!vm.keyExistsJson(json, path)) revert MissingLedgerKey(key, writtenBy);
        return vm.parseJsonUint(json, path);
    }

    /**
     * @notice Read a bytes32, reverting if absent or zero.
     * @param key       Ledger key, e.g. "permissionId".
     * @param writtenBy The script that produces it.
     */
    function word(string memory key, string memory writtenBy) internal view returns (bytes32) {
        string memory json = _read();
        string memory path = string.concat(".", key);
        if (!vm.keyExistsJson(json, path)) revert MissingLedgerKey(key, writtenBy);
        bytes32 w = vm.parseJsonBytes32(json, path);
        if (w == bytes32(0)) revert MissingLedgerKey(key, writtenBy);
        return w;
    }

    /**
     * @notice Whether a key is present AND carries a usable value.
     *
     * @dev    A key holding zero or an empty string counts as ABSENT. Anything else lets `has`
     *         answer true while the matching `addr`/`word` read reverts on the same key — which is
     *         how a cleared mandate once broke `just state` and `just preflight` at once.
     */
    function has(string memory key) internal view returns (bool) {
        string memory json = _read();
        string memory path = string.concat(".", key);
        if (!vm.keyExistsJson(json, path)) return false;

        // A ZEROED value is absent too. An address, word or number written as zero parses to
        // exactly 32 zero bytes, and `addr`/`word` already reject that — so `has` must agree, or a
        // caller that branches on `has` before reading walks into a revert.
        //
        // `clear()` removes the key outright, so it is caught by `keyExistsJson` above.
        bytes memory raw = vm.parseJson(json, path);
        if (raw.length == 0) return false;
        if (raw.length == 32) return abi.decode(raw, (bytes32)) != bytes32(0);
        return true;
    }

    // ───────────────────────────────── writes ─────────────────────────────────

    /// @notice Write an address.
    function setAddr(string memory key, address value) internal {
        _write(key, vm.toString(value));
    }

    /// @notice Write a uint.
    function setNum(string memory key, uint256 value) internal {
        _write(key, vm.toString(value));
    }

    /// @notice Write a bytes32.
    function setWord(string memory key, bytes32 value) internal {
        _write(key, vm.toString(value));
    }

    /**
     * @notice Clear a key, so `has` reports false again.
     *
     * @dev    WRITING A ZERO IS NOT CLEARING. `addr` and `word` treat zero as missing and revert,
     *         but `has` only asks whether the KEY EXISTS — so a zeroed key leaves every reader in a
     *         state where `has` says yes and the read then reverts. That is exactly the shape of a
     *         bug that stops `state` and `preflight` dead.
     *
     *         Writing the literal `null` genuinely REMOVES the key from the document — measured,
     *         not assumed — and later writes to other keys keep working. An empty string does not:
     *         it leaves a value `writeJson` then refuses to insert alongside.
     */
    function clear(string memory key) internal {
        _write(key, "null");
    }

    // ──────────────────────────────── internals ────────────────────────────────

    /// @dev An absent or empty file reads as `{}` so a first run does not have to special-case it.
    function _read() private view returns (string memory) {
        try vm.readFile(PATH) returns (string memory s) {
            return bytes(s).length == 0 ? "{}" : s;
        } catch {
            return "{}";
        }
    }

    /**
     * @dev Merge one key into the file, preserving every other key.
     *
     *      `vm.writeJson` performs a keyed update in place, so writing one value never drops the
     *      rest — which is what makes a partially-completed run resumable. The file is seeded with
     *      `{}` first if it does not exist, because `writeJson` needs a document to update.
     */
    function _write(string memory key, string memory value) private {
        try vm.readFile(PATH) returns (string memory existing) {
            if (bytes(existing).length == 0) vm.writeFile(PATH, "{}");
        } catch {
            vm.writeFile(PATH, "{}");
        }
        vm.writeJson(value, PATH, string.concat(".", key));
    }
}
